<?php
/**
 * AUTO-GENERATED by wp-cinematic from cinematic-scroll-kit schemas/scene.json
 *
 * This file is regenerated by `/wp-cinematic-scene --regenerate-schema`.
 * Hand edits OUTSIDE `@user-block:start/end` markers are LOST on regeneration.
 *
 * Placeholder shipped with __cinematic__ starter — replaced at scaffold time.
 *
 * @package __starter__
 */

defined('ABSPATH') || exit;

// @user-block:start pre-register
// Custom code that runs BEFORE the generated field group registers goes here.
// @user-block:end pre-register

// (Generated `acf_add_local_field_group()` call inserted here by the wp-cinematic agent.)
