<?php
/**
 * AUTO-GENERATED by wp-cinematic — hybrid trailing sections field group.
 *
 * Flex content layouts map 1:1 to `template-parts/section-<layout>.php`,
 * so `/wp-section` keeps working unchanged for trailing blocks.
 *
 * @package __starter__
 */

defined('ABSPATH') || exit;

// (Generated by the wp-cinematic agent when `--hybrid` mode is on.)
